version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile  # Especifica o caminho correto para o Dockerfile
    volumes:
      - ../app:/app
      - ../app/datasets:/app/datasets
    ports:
      - "8501:8501"
